-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  action text NOT NULL,
  target_id uuid,
  details jsonb,
  timestamp timestamp with time zone DEFAULT now(),
  ip_address text,
  user_agent text,
  CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_log_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.control_panel_users(id)
);
CREATE TABLE public.admin_sessions (
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  ip_address text,
  user_agent text,
  is_active boolean DEFAULT true,
  CONSTRAINT admin_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT admin_sessions_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.control_panel_users(id)
);
CREATE TABLE public.admin_trusted_devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  device_hash text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  last_used_at timestamp with time zone DEFAULT now(),
  user_agent text,
  label text,
  token_id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT admin_trusted_devices_pkey PRIMARY KEY (id),
  CONSTRAINT admin_trusted_devices_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.control_panel_users(id)
);
CREATE TABLE public.bank_info (
  user_id uuid UNIQUE,
  account_holder character varying,
  bank character varying,
  account_number character varying,
  transfer_rut character varying,
  confirmation_email text,
  account_type character varying DEFAULT 'corriente'::character varying,
  CONSTRAINT bank_info_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.banned_ips (
  ip text NOT NULL,
  banned_at timestamp with time zone DEFAULT now(),
  banned_reason text,
  banned_by uuid,
  CONSTRAINT banned_ips_pkey PRIMARY KEY (ip),
  CONSTRAINT banned_ips_banned_by_fkey FOREIGN KEY (banned_by) REFERENCES public.control_panel_users(id)
);
CREATE TABLE public.billing_info (
  user_id uuid UNIQUE,
  business_name character varying,
  billing_rut character varying,
  business_line character varying,
  billing_address text,
  billing_region text,
  billing_commune text,
  CONSTRAINT billing_info_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.cart_items (
  cart_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  price_at_addition numeric,
  price_tiers jsonb,
  cart_items_id uuid NOT NULL DEFAULT gen_random_uuid(),
  added_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  document_type text CHECK ((document_type = ANY (ARRAY['boleta'::text, 'factura'::text, 'ninguno'::text])) OR document_type IS NULL),
  offer_id uuid,
  offered_price numeric,
  metadata jsonb,
  CONSTRAINT cart_items_pkey PRIMARY KEY (cart_items_id),
  CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(cart_id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid)
);
CREATE TABLE public.carts (
  user_id uuid NOT NULL,
  cart_id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  shipping_total integer,
  shipping_currency text DEFAULT 'CLP'::text,
  payment_order_id uuid,
  supplier_id uuid,
  CONSTRAINT carts_pkey PRIMARY KEY (cart_id),
  CONSTRAINT carts_payment_order_id_fkey FOREIGN KEY (payment_order_id) REFERENCES public.orders(id),
  CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.control_panel (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL UNIQUE,
  proveedor text NOT NULL,
  comprador text NOT NULL,
  ticket text NOT NULL,
  direccion_entrega text,
  fecha_solicitada date NOT NULL,
  fecha_entrega date,
  venta numeric NOT NULL,
  estado text NOT NULL DEFAULT 'pendiente'::text CHECK (estado = ANY (ARRAY['pendiente'::text, 'confirmado'::text, 'rechazado'::text, 'devuelto'::text, 'en_proceso'::text, 'entregado'::text])),
  acciones text,
  comprobante_pago text,
  notas_admin text,
  procesado_por uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT control_panel_pkey PRIMARY KEY (id),
  CONSTRAINT control_panel_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(request_id),
  CONSTRAINT control_panel_procesado_por_fkey FOREIGN KEY (procesado_por) REFERENCES public.control_panel_users(id)
);
CREATE TABLE public.control_panel_users (
  usuario text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  last_login timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  email text UNIQUE,
  full_name text,
  role text DEFAULT 'admin'::text CHECK (role = 'admin'::text),
  twofa_secret text,
  notes text,
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  twofa_required boolean DEFAULT true,
  twofa_configured boolean DEFAULT false,
  needs_password_change boolean DEFAULT false,
  CONSTRAINT control_panel_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.edge_function_invocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  function_name text NOT NULL,
  request_id uuid DEFAULT gen_random_uuid(),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  duration_ms integer,
  status text NOT NULL CHECK (status = ANY (ARRAY['success'::text, 'error'::text])),
  error_code text,
  error_message text,
  request_origin text,
  input_size_bytes integer,
  output_size_bytes integer,
  meta jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT edge_function_invocations_pkey PRIMARY KEY (id),
  CONSTRAINT edge_function_invocations_function_name_fkey FOREIGN KEY (function_name) REFERENCES public.edge_functions(function_name)
);
CREATE TABLE public.edge_functions (
  function_name text NOT NULL,
  display_name text,
  category text,
  owner text,
  sla_ms integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT edge_functions_pkey PRIMARY KEY (function_name)
);
CREATE TABLE public.ejemplo (
  id bigint NOT NULL DEFAULT nextval('ejemplo_id_seq'::regclass),
  nombre text,
  CONSTRAINT ejemplo_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ejemplo_prueba (
  id bigint NOT NULL DEFAULT nextval('ejemplo_prueba_id_seq'::regclass),
  nombre text,
  CONSTRAINT ejemplo_prueba_pkey PRIMARY KEY (id)
);
CREATE TABLE public.flow_webhook_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  flow_order bigint,
  commerce_order character varying,
  token character varying,
  status integer,
  webhook_data jsonb,
  signature_valid boolean DEFAULT true,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  processing_latency_ms integer,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  order_id uuid,
  category text,
  CONSTRAINT flow_webhook_logs_pkey PRIMARY KEY (id),
  CONSTRAINT flow_webhook_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.image_orphan_candidates (
  path text NOT NULL,
  detected_at timestamp with time zone NOT NULL DEFAULT now(),
  last_seen_reference timestamp with time zone,
  confirmed_deleted_at timestamp with time zone,
  bucket text NOT NULL CHECK (bucket = ANY (ARRAY['product-images'::text, 'product-images-thumbnails'::text])),
  CONSTRAINT image_orphan_candidates_pkey PRIMARY KEY (path)
);
CREATE TABLE public.image_thumbnail_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  product_image_id uuid,
  status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'processing'::text, 'success'::text, 'error'::text])),
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  duration_ms integer,
  error_code text,
  CONSTRAINT image_thumbnail_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT image_thumbnail_jobs_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid),
  CONSTRAINT image_thumbnail_jobs_product_image_id_fkey FOREIGN KEY (product_image_id) REFERENCES public.product_images(id)
);
CREATE TABLE public.invoices_meta (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  supplier_id uuid,
  order_id uuid,
  path text NOT NULL,
  filename text,
  size integer,
  content_type text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_meta_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_meta_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT invoices_meta_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id),
  CONSTRAINT invoices_meta_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.khipu_webhook_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id character varying,
  transaction_id character varying,
  status character varying,
  webhook_data jsonb,
  signature_header text,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  order_id uuid,
  signature_valid boolean DEFAULT true,
  category text,
  processing_latency_ms integer,
  CONSTRAINT khipu_webhook_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  supplier_id uuid,
  order_id uuid,
  product_id uuid,
  type text NOT NULL,
  order_status text,
  role_context text NOT NULL DEFAULT 'buyer'::text,
  context_section text NOT NULL DEFAULT 'generic'::text,
  title text NOT NULL,
  body text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT notifications_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id),
  CONSTRAINT notifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT notifications_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid)
);
CREATE TABLE public.offer_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  product_id uuid,
  supplier_id uuid NOT NULL,
  month_year text NOT NULL,
  product_offers_count integer DEFAULT 1 CHECK (product_offers_count >= 0),
  supplier_offers_count integer DEFAULT 1 CHECK (supplier_offers_count >= 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offer_limits_pkey PRIMARY KEY (id),
  CONSTRAINT offer_limits_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(user_id),
  CONSTRAINT offer_limits_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid),
  CONSTRAINT offer_limits_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.offer_limits_product (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  product_id uuid NOT NULL,
  month_year text NOT NULL,
  offers_count integer NOT NULL DEFAULT 1 CHECK (offers_count >= 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offer_limits_product_pkey PRIMARY KEY (id),
  CONSTRAINT offer_limits_product_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(user_id),
  CONSTRAINT offer_limits_product_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid)
);
CREATE TABLE public.offer_limits_supplier (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  month_year text NOT NULL,
  offers_count integer NOT NULL DEFAULT 1 CHECK (offers_count >= 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offer_limits_supplier_pkey PRIMARY KEY (id),
  CONSTRAINT offer_limits_supplier_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(user_id),
  CONSTRAINT offer_limits_supplier_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  product_id uuid NOT NULL,
  offered_price numeric NOT NULL CHECK (offered_price > 0::numeric),
  offered_quantity integer NOT NULL CHECK (offered_quantity > 0),
  message text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'accepted'::text, 'reserved'::text, 'paid'::text, 'cancelled'::text, 'rejected'::text, 'expired'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  purchase_deadline timestamp with time zone,
  purchased_at timestamp with time zone,
  rejected_at timestamp with time zone,
  expired_at timestamp with time zone,
  tier_price_at_offer numeric,
  base_price_at_offer numeric NOT NULL,
  stock_reserved boolean DEFAULT false,
  reserved_at timestamp with time zone,
  rejection_reason text,
  updated_at timestamp with time zone DEFAULT now(),
  order_id uuid,
  hidden_by_buyer boolean DEFAULT false,
  hidden_by_supplier boolean DEFAULT false,
  CONSTRAINT offers_pkey PRIMARY KEY (id),
  CONSTRAINT offers_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(user_id),
  CONSTRAINT offers_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id),
  CONSTRAINT offers_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid),
  CONSTRAINT offers_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  items jsonb NOT NULL,
  subtotal numeric NOT NULL DEFAULT 0,
  tax numeric NOT NULL DEFAULT 0,
  shipping numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  currency character varying NOT NULL DEFAULT 'CLP'::character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'in_transit'::character varying, 'delivered'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'rejected'::character varying]::text[])),
  payment_method character varying,
  payment_status character varying NOT NULL DEFAULT 'pending'::character varying,
  shipping_address jsonb,
  billing_address jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  khipu_payment_id character varying,
  khipu_transaction_id character varying,
  khipu_payment_url text,
  khipu_expires_at timestamp with time zone DEFAULT (now() + '00:20:00'::interval),
  paid_at timestamp with time zone,
  fulfillment_status text,
  accepted_at timestamp with time zone,
  dispatched_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  rejection_reason text,
  cancellation_reason text,
  cart_id uuid,
  estimated_delivery_date timestamp with time zone,
  split_status text DEFAULT 'not_split'::text CHECK (split_status = ANY (ARRAY['not_split'::text, 'split'::text, 'partial'::text])),
  pricing_verified_at timestamp with time zone,
  items_hash text,
  inventory_processed_at timestamp with time zone,
  supplier_ids ARRAY,
  supplier_parts_meta jsonb,
  payment_fee numeric DEFAULT 0,
  grand_total numeric,
  hidden_by_buyer boolean DEFAULT false,
  flow_order bigint,
  flow_token character varying,
  flow_payment_url text,
  flow_expires_at timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.payment_releases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  buyer_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'CLP'::text,
  delivery_confirmed_at timestamp with time zone NOT NULL,
  payment_received_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'pending_release'::text CHECK (status = ANY (ARRAY['pending_release'::text, 'released'::text, 'cancelled'::text, 'disputed'::text])),
  released_by_admin_id uuid,
  released_at timestamp with time zone,
  admin_notes text,
  payment_proof_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_releases_pkey PRIMARY KEY (id),
  CONSTRAINT payment_releases_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT payment_releases_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id),
  CONSTRAINT payment_releases_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(user_id),
  CONSTRAINT payment_releases_released_by_admin_id_fkey FOREIGN KEY (released_by_admin_id) REFERENCES public.control_panel_users(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  payment_method character varying NOT NULL,
  external_payment_id character varying,
  external_transaction_id character varying,
  amount numeric NOT NULL,
  currency character varying NOT NULL DEFAULT 'CLP'::character varying,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  gateway_response jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.polling_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  function_name character varying NOT NULL,
  processed integer DEFAULT 0,
  updated integer DEFAULT 0,
  errors integer DEFAULT 0,
  duration_ms integer,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT polling_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_delivery_regions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  region text NOT NULL,
  price numeric NOT NULL,
  delivery_days integer NOT NULL,
  CONSTRAINT product_delivery_regions_pkey PRIMARY KEY (id),
  CONSTRAINT product_delivery_regions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid)
);
CREATE TABLE public.product_images (
  product_id uuid NOT NULL,
  image_url text NOT NULL,
  thumbnail_url text,
  thumbnails jsonb,
  image_order integer NOT NULL DEFAULT 0 CHECK (image_order >= 0),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  thumbnail_signature text,
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid)
);
CREATE TABLE public.product_quantity_ranges (
  product_qty_id uuid NOT NULL DEFAULT gen_random_uuid(),
  price numeric NOT NULL DEFAULT 0.00,
  product_id uuid,
  min_quantity integer NOT NULL,
  max_quantity integer,
  CONSTRAINT product_quantity_ranges_pkey PRIMARY KEY (product_qty_id),
  CONSTRAINT product_quantity_ranges_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid)
);
CREATE TABLE public.product_sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  amount numeric NOT NULL DEFAULT 0,
  trx_date timestamp with time zone NOT NULL DEFAULT now(),
  order_id uuid,
  CONSTRAINT product_sales_pkey PRIMARY KEY (id),
  CONSTRAINT product_sales_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT product_sales_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid),
  CONSTRAINT product_sales_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.products (
  productnm text NOT NULL,
  supplier_id uuid,
  category character varying,
  description text,
  max_quantity integer,
  productid uuid NOT NULL DEFAULT gen_random_uuid(),
  productqty integer NOT NULL DEFAULT 0,
  price numeric NOT NULL DEFAULT 0.00,
  minimum_purchase integer DEFAULT 1,
  negotiable boolean DEFAULT false,
  product_type character varying DEFAULT 'general'::character varying,
  min_quantity integer DEFAULT 1,
  spec_name character varying NOT NULL DEFAULT 'N/A'::character varying,
  spec_value text NOT NULL DEFAULT 'N/A'::text,
  is_active boolean DEFAULT true,
  createddt timestamp with time zone NOT NULL DEFAULT now(),
  updateddt timestamp with time zone NOT NULL DEFAULT now(),
  deletion_status text DEFAULT 'active'::text CHECK (deletion_status = ANY (ARRAY['active'::text, 'pending_delete'::text, 'archived'::text])),
  deletion_requested_at timestamp with time zone,
  safe_delete_after timestamp with time zone,
  tiny_thumbnail_url text,
  free_shipping_enabled boolean DEFAULT false,
  free_shipping_min_quantity integer,
  CONSTRAINT products_pkey PRIMARY KEY (productid),
  CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.request_products (
  request_id uuid,
  product_id uuid,
  quantity integer NOT NULL,
  request_product_id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT request_products_pkey PRIMARY KEY (request_product_id),
  CONSTRAINT request_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid),
  CONSTRAINT request_products_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(request_id)
);
CREATE TABLE public.requests (
  delivery_country text NOT NULL,
  delivery_region text NOT NULL,
  delivery_commune text NOT NULL,
  delivery_direction text NOT NULL,
  delivery_direction_number text NOT NULL,
  delivery_direction_dept text NOT NULL,
  request_dt date NOT NULL,
  delivery_dt date,
  total_sale numeric,
  label text NOT NULL,
  buyer_id uuid,
  request_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_dt timestamp without time zone DEFAULT now(),
  CONSTRAINT requests_pkey PRIMARY KEY (request_id),
  CONSTRAINT requests_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.sales (
  user_id uuid NOT NULL,
  amount numeric NOT NULL,
  trx_date timestamp with time zone DEFAULT now(),
  trx_id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT sales_pkey PRIMARY KEY (trx_id),
  CONSTRAINT sales_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.shipping_info (
  user_id uuid UNIQUE,
  shipping_region text,
  shipping_commune text,
  shipping_address text,
  shipping_number text,
  shipping_dept text,
  CONSTRAINT shipping_info_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.storage_cleanup_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  executed_at timestamp with time zone NOT NULL DEFAULT now(),
  products_processed integer NOT NULL DEFAULT 0,
  files_removed integer NOT NULL DEFAULT 0,
  execution_time_ms integer NOT NULL DEFAULT 0,
  errors jsonb DEFAULT '[]'::jsonb,
  success boolean NOT NULL DEFAULT true,
  trigger_type text DEFAULT 'scheduled'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT storage_cleanup_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.supplier_billing_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL UNIQUE,
  rut_emisor character varying NOT NULL CHECK (rut_emisor::text ~ '^[0-9]{1,8}-[0-9Kk]$'::text),
  razon_social character varying NOT NULL,
  giro character varying NOT NULL,
  direccion character varying NOT NULL,
  comuna character varying NOT NULL,
  ciudad character varying,
  actividades_economicas ARRAY DEFAULT '{469000}'::integer[] CHECK (actividades_economicas IS NULL OR array_length(actividades_economicas, 1) > 0),
  sucursal character varying,
  codigo_sucursal integer CHECK (codigo_sucursal IS NULL OR codigo_sucursal >= 0),
  numero_resolucion integer DEFAULT 0 CHECK (numero_resolucion >= 0),
  fecha_resolucion date,
  ambiente character varying DEFAULT 'CERT'::character varying CHECK (ambiente::text = ANY (ARRAY['CERT'::character varying, 'PROD'::character varying]::text[])),
  email_dte character varying CHECK (email_dte IS NULL OR email_dte::text ~ '^[^@]+@[^@]+\.[^@]+$'::text),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_billing_config_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_billing_config_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.supplier_cafs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  tipo_dte smallint NOT NULL CHECK (tipo_dte = ANY (ARRAY[33, 34, 39, 41, 52, 56, 61])),
  folio_desde integer NOT NULL CHECK (folio_desde >= 1 AND folio_desde <= 999999999),
  folio_hasta integer NOT NULL CHECK (folio_hasta >= 1 AND folio_hasta <= 999999999),
  folio_actual integer NOT NULL CHECK (folio_actual >= 1),
  caf_xml_encrypted text NOT NULL,
  caf_iv character varying NOT NULL,
  caf_auth_tag character varying NOT NULL,
  is_active boolean DEFAULT true,
  agotado boolean DEFAULT false,
  fecha_autorizacion date NOT NULL,
  fecha_vencimiento date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_cafs_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_cafs_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.supplier_certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  rut_titular character varying NOT NULL CHECK (rut_titular::text ~ '^[0-9]{1,8}-[0-9Kk]$'::text),
  nombre_titular character varying NOT NULL,
  pfx_encrypted text NOT NULL,
  iv character varying NOT NULL,
  auth_tag character varying NOT NULL,
  passphrase_hash character varying,
  valid_from timestamp with time zone NOT NULL,
  valid_to timestamp with time zone NOT NULL,
  fingerprint character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_certificates_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_certificates_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.supplier_dtes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  tipo_dte smallint NOT NULL CHECK (tipo_dte = ANY (ARRAY[33, 34, 39, 41, 52, 56, 61])),
  folio integer NOT NULL CHECK (folio >= 1 AND folio <= 999999999),
  fecha_emision date NOT NULL CHECK (fecha_emision <= CURRENT_DATE),
  rut_receptor character varying NOT NULL CHECK (rut_receptor::text ~ '^[0-9]{1,8}-[0-9Kk]$'::text),
  razon_social_receptor character varying NOT NULL,
  giro_receptor character varying,
  direccion_receptor character varying,
  comuna_receptor character varying,
  ciudad_receptor character varying,
  monto_neto bigint CHECK (monto_neto IS NULL OR monto_neto >= 0),
  monto_exento bigint CHECK (monto_exento IS NULL OR monto_exento >= 0),
  iva bigint CHECK (iva IS NULL OR iva >= 0),
  monto_total bigint NOT NULL CHECK (monto_total >= 0),
  ind_servicio smallint CHECK (ind_servicio IS NULL OR (ind_servicio = ANY (ARRAY[1, 2, 3]))),
  forma_pago smallint CHECK (forma_pago IS NULL OR (forma_pago = ANY (ARRAY[1, 2, 3]))),
  track_id character varying,
  estado character varying DEFAULT 'PENDIENTE'::character varying CHECK (estado::text = ANY (ARRAY['PENDIENTE'::character varying, 'ENVIADO'::character varying, 'ACEPTADO'::character varying, 'RECHAZADO'::character varying, 'ACEPTADO_CON_REPAROS'::character varying, 'ANULADO'::character varying, 'SIMULADO'::character varying, 'ERROR'::character varying]::text[])),
  glosa_estado character varying,
  fecha_aceptacion timestamp with time zone,
  dte_referencia_id uuid,
  dte_referencia_tipo smallint CHECK (dte_referencia_tipo IS NULL OR (dte_referencia_tipo = ANY (ARRAY[33, 34, 39, 41, 52, 56, 61]))),
  dte_referencia_folio integer CHECK (dte_referencia_folio IS NULL OR dte_referencia_folio >= 1 AND dte_referencia_folio <= 999999999),
  dte_referencia_fecha date,
  codigo_referencia smallint CHECK (codigo_referencia IS NULL OR (codigo_referencia = ANY (ARRAY[1, 2, 3]))),
  razon_referencia character varying,
  xml_firmado text,
  ted_xml text,
  detalle_items jsonb,
  supplier_order_id uuid,
  parent_order_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  estado_sii character varying,
  glosa_sii text,
  CONSTRAINT supplier_dtes_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_dtes_parent_order_id_fkey FOREIGN KEY (parent_order_id) REFERENCES public.orders(id),
  CONSTRAINT supplier_dtes_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id),
  CONSTRAINT supplier_dtes_dte_referencia_id_fkey FOREIGN KEY (dte_referencia_id) REFERENCES public.supplier_dtes(id),
  CONSTRAINT supplier_dtes_supplier_order_id_fkey FOREIGN KEY (supplier_order_id) REFERENCES public.supplier_orders(id)
);
CREATE TABLE public.supplier_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL DEFAULT 0,
  price_at_addition numeric,
  price_tiers jsonb,
  document_type text CHECK ((document_type = ANY (ARRAY['boleta'::text, 'factura'::text, 'ninguno'::text])) OR document_type IS NULL),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT supplier_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_order_items_supplier_order_id_fkey FOREIGN KEY (supplier_order_id) REFERENCES public.supplier_orders(id),
  CONSTRAINT supplier_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(productid)
);
CREATE TABLE public.supplier_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_order_id uuid NOT NULL,
  supplier_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'in_transit'::text, 'delivered'::text, 'cancelled'::text, 'rejected'::text])),
  payment_status text NOT NULL DEFAULT 'pending'::text,
  estimated_delivery_date timestamp with time zone,
  subtotal numeric NOT NULL DEFAULT 0,
  shipping_amount numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  delivered_at timestamp with time zone,
  dte_tipo smallint CHECK (dte_tipo IS NULL OR (dte_tipo = ANY (ARRAY[33, 34, 39, 41, 52, 56, 61]))),
  dte_folio integer CHECK (dte_folio IS NULL OR dte_folio >= 1 AND dte_folio <= 999999999),
  dte_fecha_emision date,
  dte_estado character varying CHECK (dte_estado IS NULL OR (dte_estado::text = ANY (ARRAY['PENDIENTE'::character varying, 'ENVIADO'::character varying, 'ACEPTADO'::character varying, 'RECHAZADO'::character varying, 'ACEPTADO_CON_REPAROS'::character varying, 'ANULADO'::character varying, 'SIMULADO'::character varying, 'ERROR'::character varying]::text[]))),
  dte_id uuid,
  CONSTRAINT supplier_orders_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_orders_parent_order_id_fkey FOREIGN KEY (parent_order_id) REFERENCES public.orders(id),
  CONSTRAINT supplier_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id),
  CONSTRAINT supplier_orders_dte_id_fkey FOREIGN KEY (dte_id) REFERENCES public.supplier_dtes(id)
);
CREATE TABLE public.supplier_secrets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL UNIQUE,
  passphrase_encrypted text,
  passphrase_iv character varying,
  passphrase_auth_tag character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_secrets_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_secrets_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.supplier_shipping_region_presets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  preset_index smallint NOT NULL CHECK (preset_index >= 1 AND preset_index <= 3),
  name text NOT NULL,
  regions jsonb NOT NULL CHECK (jsonb_typeof(regions) = 'array'::text),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_shipping_region_presets_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_shipping_region_presets_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.users (
  rut character varying,
  user_id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  user_nm character varying NOT NULL,
  phone_nbr character varying,
  country text NOT NULL,
  logo_url text,
  main_supplier boolean NOT NULL DEFAULT false,
  createdt timestamp with time zone NOT NULL DEFAULT now(),
  updatedt timestamp with time zone NOT NULL DEFAULT now(),
  descripcion_proveedor text,
  banned boolean NOT NULL DEFAULT false,
  banned_at timestamp with time zone,
  banned_reason text,
  verified boolean NOT NULL DEFAULT false,
  verified_at timestamp with time zone,
  verified_by uuid,
  last_ip text,
  document_types ARRAY DEFAULT '{}'::text[] CHECK (document_types <@ ARRAY['ninguno'::text, 'boleta'::text, 'factura'::text]),
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);