# .github/workflows/deploy.yml
name: Deploy Supabase Migrations

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "Deploying to Staging..."
          supabase link --project-ref ${{ secrets.STAGING_PROJECT_ID }}
          supabase db push

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Production..."
          supabase link --project-ref ${{ secrets.PRODUCTION_PROJECT_ID }}
          supabase db push
