// Datos de regiones, ciudades y comunas de Chile
export const regiones = [
  { value: 'arica-parinacota', label: 'Arica y Parinacota' },
  { value: 'tarapaca', label: 'Tarapacá' },
  { value: 'antofagasta', label: 'Antofagasta' },
  { value: 'atacama', label: 'Atacama' },
  { value: 'coquimbo', label: 'Coquimbo' },
  { value: 'valparaiso', label: 'Valparaíso' },
  { value: 'metropolitana', label: 'Región Metropolitana' },
  { value: 'ohiggins', label: "O'Higgins" },
  { value: 'maule', label: 'Maule' },
  { value: 'nuble', label: 'Ñuble' },
  { value: 'biobio', label: 'Biobío' },
  { value: 'araucania', label: 'La Araucanía' },
  { value: 'los-rios', label: 'Los Ríos' },
  { value: 'los-lagos', label: 'Los Lagos' },
  { value: 'aysen', label: 'Aysén' },
  { value: 'magallanes', label: 'Magallanes y Antártica Chilena' },
];

export const ciudadesPorRegion = {
  'arica-parinacota': [
    { value: 'arica', label: 'Arica' },
  ],
  'tarapaca': [
    { value: 'iquique', label: 'Iquique' },
  ],
  'antofagasta': [
    { value: 'antofagasta', label: 'Antofagasta' },
    { value: 'calama', label: 'Calama' },
  ],
  'atacama': [
    { value: 'copiapo', label: 'Copiapó' },
    { value: 'vallenar', label: 'Vallenar' },
  ],
  'coquimbo': [
    { value: 'la-serena', label: 'La Serena' },
    { value: 'coquimbo', label: 'Coquimbo' },
    { value: 'ovalle', label: 'Ovalle' },
  ],
  'valparaiso': [
    { value: 'valparaiso', label: 'Valparaíso' },
    { value: 'vina-del-mar', label: 'Viña del Mar' },
    { value: 'san-antonio', label: 'San Antonio' },
    { value: 'quilpue', label: 'Quilpué' },
  ],
  'metropolitana': [
    { value: 'santiago', label: 'Santiago' },
    { value: 'puente-alto', label: 'Puente Alto' },
    { value: 'maipu', label: 'Maipú' },
  ],
  'ohiggins': [
    { value: 'rancagua', label: 'Rancagua' },
    { value: 'san-fernando', label: 'San Fernando' },
  ],
  'maule': [
    { value: 'talca', label: 'Talca' },
    { value: 'curico', label: 'Curicó' },
    { value: 'linares', label: 'Linares' },
  ],
  'nuble': [
    { value: 'chillan', label: 'Chillán' },
  ],
  'biobio': [
    { value: 'concepcion', label: 'Concepción' },
    { value: 'los-angeles', label: 'Los Ángeles' },
    { value: 'talcahuano', label: 'Talcahuano' },
  ],
  'araucania': [
    { value: 'temuco', label: 'Temuco' },
    { value: 'villarrica', label: 'Villarrica' },
  ],
  'los-rios': [
    { value: 'valdivia', label: 'Valdivia' },
  ],
  'los-lagos': [
    { value: 'puerto-montt', label: 'Puerto Montt' },
    { value: 'osorno', label: 'Osorno' },
    { value: 'castro', label: 'Castro' },
  ],
  'aysen': [
    { value: 'coyhaique', label: 'Coyhaique' },
  ],
  'magallanes': [
    { value: 'punta-arenas', label: 'Punta Arenas' },
    { value: 'puerto-natales', label: 'Puerto Natales' },
  ],
};

export const comunasPorRegion = {
  'arica-parinacota': [
    { value: 'arica', label: 'Arica' },
    { value: 'camarones', label: 'Camarones' },
    { value: 'putre', label: 'Putre' },
    { value: 'general-lagos', label: 'General Lagos' },
  ],
  'tarapaca': [
    { value: 'iquique', label: 'Iquique' },
    { value: 'alto-hospicio', label: 'Alto Hospicio' },
    { value: 'pozo-almonte', label: 'Pozo Almonte' },
    { value: 'camina', label: 'Camiña' },
    { value: 'colchane', label: 'Colchane' },
    { value: 'huara', label: 'Huara' },
    { value: 'pica', label: 'Pica' },
  ],
  'antofagasta': [
    { value: 'antofagasta', label: 'Antofagasta' },
    { value: 'mejillones', label: 'Mejillones' },
    { value: 'sierra-gorda', label: 'Sierra Gorda' },
    { value: 'taltal', label: 'Taltal' },
    { value: 'calama', label: 'Calama' },
    { value: 'ollague', label: 'Ollagüe' },
    { value: 'san-pedro-de-atacama', label: 'San Pedro de Atacama' },
    { value: 'tocopilla', label: 'Tocopilla' },
    { value: 'maria-elena', label: 'María Elena' },
  ],
  'atacama': [
    { value: 'copiapo', label: 'Copiapó' },
    { value: 'caldera', label: 'Caldera' },
    { value: 'tierra-amarilla', label: 'Tierra Amarilla' },
    { value: 'chanaral', label: 'Chañaral' },
    { value: 'diego-de-almagro', label: 'Diego de Almagro' },
    { value: 'vallenar', label: 'Vallenar' },
    { value: 'alto-del-carmen', label: 'Alto del Carmen' },
    { value: 'freirina', label: 'Freirina' },
    { value: 'huasco', label: 'Huasco' },
  ],
  'coquimbo': [
    { value: 'la-serena', label: 'La Serena' },
    { value: 'coquimbo', label: 'Coquimbo' },
    { value: 'andacollo', label: 'Andacollo' },
    { value: 'la-higuera', label: 'La Higuera' },
    { value: 'paiguano', label: 'Paiguano' },
    { value: 'vicuna', label: 'Vicuña' },
    { value: 'illapel', label: 'Illapel' },
    { value: 'canela', label: 'Canela' },
    { value: 'los-vilos', label: 'Los Vilos' },
    { value: 'salamanca', label: 'Salamanca' },
    { value: 'ovalle', label: 'Ovalle' },
    { value: 'combarbala', label: 'Combarbalá' },
    { value: 'monte-patria', label: 'Monte Patria' },
    { value: 'punitaqui', label: 'Punitaqui' },
    { value: 'rio-hurtado', label: 'Río Hurtado' },
  ],
  'valparaiso': [
    { value: 'valparaiso', label: 'Valparaíso' },
    { value: 'casablanca', label: 'Casablanca' },
    { value: 'concon', label: 'Concón' },
    { value: 'juan-fernandez', label: 'Juan Fernández' },
    { value: 'puchuncavi', label: 'Puchuncaví' },
    { value: 'quintero', label: 'Quintero' },
    { value: 'vina-del-mar', label: 'Viña del Mar' },
    { value: 'isla-de-pascua', label: 'Isla de Pascua' },
    { value: 'los-andes', label: 'Los Andes' },
    { value: 'calle-larga', label: 'Calle Larga' },
    { value: 'rinconada', label: 'Rinconada' },
    { value: 'san-esteban', label: 'San Esteban' },
    { value: 'la-ligua', label: 'La Ligua' },
    { value: 'cabildo', label: 'Cabildo' },
    { value: 'papudo', label: 'Papudo' },
    { value: 'petorca', label: 'Petorca' },
    { value: 'zapallar', label: 'Zapallar' },
    { value: 'quillota', label: 'Quillota' },
    { value: 'calera', label: 'Calera' },
    { value: 'hijuelas', label: 'Hijuelas' },
    { value: 'la-cruz', label: 'La Cruz' },
    { value: 'limache', label: 'Limache' },
    { value: 'nogales', label: 'Nogales' },
    { value: 'olmue', label: 'Olmué' },
    { value: 'san-antonio', label: 'San Antonio' },
    { value: 'algarrobo', label: 'Algarrobo' },
    { value: 'cartagena', label: 'Cartagena' },
    { value: 'el-quisco', label: 'El Quisco' },
    { value: 'el-tabo', label: 'El Tabo' },
    { value: 'santo-domingo', label: 'Santo Domingo' },
    { value: 'san-felipe', label: 'San Felipe' },
    { value: 'catemu', label: 'Catemu' },
    { value: 'llaillay', label: 'Llaillay' },
    { value: 'panquehue', label: 'Panquehue' },
    { value: 'putaendo', label: 'Putaendo' },
    { value: 'santa-maria', label: 'Santa María' },
    { value: 'quilpue', label: 'Quilpué' },
    { value: 'villa-alemana', label: 'Villa Alemana' },
  ],
  'metropolitana': [
    { value: 'cerrillos', label: 'Cerrillos' },
    { value: 'cerro-navia', label: 'Cerro Navia' },
    { value: 'conchali', label: 'Conchalí' },
    { value: 'el-bosque', label: 'El Bosque' },
    { value: 'estacion-central', label: 'Estación Central' },
    { value: 'huechuraba', label: 'Huechuraba' },
    { value: 'independencia', label: 'Independencia' },
    { value: 'la-cisterna', label: 'La Cisterna' },
    { value: 'la-florida', label: 'La Florida' },
    { value: 'la-granja', label: 'La Granja' },
    { value: 'la-pintana', label: 'La Pintana' },
    { value: 'la-reina', label: 'La Reina' },
    { value: 'las-condes', label: 'Las Condes' },
    { value: 'lo-barnechea', label: 'Lo Barnechea' },
    { value: 'lo-espejo', label: 'Lo Espejo' },
    { value: 'lo-prado', label: 'Lo Prado' },
    { value: 'macul', label: 'Macul' },
    { value: 'maipu', label: 'Maipú' },
    { value: 'nunoa', label: 'Ñuñoa' },
    { value: 'pedro-aguirre-cerda', label: 'Pedro Aguirre Cerda' },
    { value: 'penalolen', label: 'Peñalolén' },
    { value: 'providencia', label: 'Providencia' },
    { value: 'pudahuel', label: 'Pudahuel' },
    { value: 'quilicura', label: 'Quilicura' },
    { value: 'quinta-normal', label: 'Quinta Normal' },
    { value: 'recoleta', label: 'Recoleta' },
    { value: 'renca', label: 'Renca' },
    { value: 'san-joaquin', label: 'San Joaquín' },
    { value: 'san-miguel', label: 'San Miguel' },
    { value: 'san-ramon', label: 'San Ramón' },
    { value: 'santiago', label: 'Santiago' },
    { value: 'vitacura', label: 'Vitacura' },
    { value: 'puente-alto', label: 'Puente Alto' },
    { value: 'pirque', label: 'Pirque' },
    { value: 'san-jose-de-maipo', label: 'San José de Maipo' },
    { value: 'colina', label: 'Colina' },
    { value: 'lampa', label: 'Lampa' },
    { value: 'tiltil', label: 'Tiltil' },
    { value: 'san-bernardo', label: 'San Bernardo' },
    { value: 'buin', label: 'Buin' },
    { value: 'calera-de-tango', label: 'Calera de Tango' },
    { value: 'paine', label: 'Paine' },
    { value: 'melipilla', label: 'Melipilla' },
    { value: 'alhue', label: 'Alhué' },
    { value: 'curacavi', label: 'Curacaví' },
    { value: 'maria-pinto', label: 'María Pinto' },
    { value: 'san-pedro', label: 'San Pedro' },
    { value: 'talagante', label: 'Talagante' },
    { value: 'el-monte', label: 'El Monte' },
    { value: 'isla-de-maipo', label: 'Isla de Maipo' },
    { value: 'padre-hurtado', label: 'Padre Hurtado' },
    { value: 'penaflor', label: 'Peñaflor' },
  ],
  'ohiggins': [
    { value: 'rancagua', label: 'Rancagua' },
    { value: 'codegua', label: 'Codegua' },
    { value: 'coinco', label: 'Coinco' },
    { value: 'coltauco', label: 'Coltauco' },
    { value: 'donihue', label: 'Doñihue' },
    { value: 'graneros', label: 'Graneros' },
    { value: 'las-cabras', label: 'Las Cabras' },
    { value: 'machali', label: 'Machalí' },
    { value: 'malloa', label: 'Malloa' },
    { value: 'mostazal', label: 'Mostazal' },
    { value: 'olivar', label: 'Olivar' },
    { value: 'peumo', label: 'Peumo' },
    { value: 'pichidegua', label: 'Pichidegua' },
    { value: 'quinta-de-tilcoco', label: 'Quinta de Tilcoco' },
    { value: 'requinoa', label: 'Requínoa' },
    { value: 'rengo', label: 'Rengo' },
    { value: 'san-vicente', label: 'San Vicente' },
    { value: 'pichilemu', label: 'Pichilemu' },
    { value: 'la-estrella', label: 'La Estrella' },
    { value: 'litueche', label: 'Litueche' },
    { value: 'marchihue', label: 'Marchihue' },
    { value: 'navidad', label: 'Navidad' },
    { value: 'paredones', label: 'Paredones' },
    { value: 'san-fernando', label: 'San Fernando' },
    { value: 'chepica', label: 'Chépica' },
    { value: 'chimbarongo', label: 'Chimbarongo' },
    { value: 'lolol', label: 'Lolol' },
    { value: 'nancagua', label: 'Nancagua' },
    { value: 'palmilla', label: 'Palmilla' },
    { value: 'peralillo', label: 'Peralillo' },
    { value: 'placilla', label: 'Placilla' },
    { value: 'pumanque', label: 'Pumanque' },
    { value: 'santa-cruz', label: 'Santa Cruz' },
  ],
  'maule': [
    { value: 'talca', label: 'Talca' },
    { value: 'constitucion', label: 'Constitución' },
    { value: 'curepto', label: 'Curepto' },
    { value: 'empedrado', label: 'Empedrado' },
    { value: 'maule', label: 'Maule' },
    { value: 'pelarco', label: 'Pelarco' },
    { value: 'pencahue', label: 'Pencahue' },
    { value: 'rio-claro', label: 'Río Claro' },
    { value: 'san-clemente', label: 'San Clemente' },
    { value: 'san-rafael', label: 'San Rafael' },
    { value: 'curico', label: 'Curicó' },
    { value: 'hualane', label: 'Hualañé' },
    { value: 'licanten', label: 'Licantén' },
    { value: 'molina', label: 'Molina' },
    { value: 'rauco', label: 'Rauco' },
    { value: 'romeral', label: 'Romeral' },
    { value: 'sagrada-familia', label: 'Sagrada Familia' },
    { value: 'teno', label: 'Teno' },
    { value: 'vichuquen', label: 'Vichuquén' },
    { value: 'linares', label: 'Linares' },
    { value: 'colbun', label: 'Colbún' },
    { value: 'longavi', label: 'Longaví' },
    { value: 'parral', label: 'Parral' },
    { value: 'retiro', label: 'Retiro' },
    { value: 'san-javier', label: 'San Javier' },
    { value: 'villa-alegre', label: 'Villa Alegre' },
    { value: 'yerbas-buenas', label: 'Yerbas Buenas' },
    { value: 'cauquenes', label: 'Cauquenes' },
    { value: 'chanco', label: 'Chanco' },
    { value: 'pelluhue', label: 'Pelluhue' },
  ],
  'nuble': [
    { value: 'chillan', label: 'Chillán' },
    { value: 'bulnes', label: 'Bulnes' },
    { value: 'chillan-viejo', label: 'Chillán Viejo' },
    { value: 'el-carmen', label: 'El Carmen' },
    { value: 'pemuco', label: 'Pemuco' },
    { value: 'pinto', label: 'Pinto' },
    { value: 'quillon', label: 'Quillón' },
    { value: 'san-ignacio', label: 'San Ignacio' },
    { value: 'yungay', label: 'Yungay' },
    { value: 'cobquecura', label: 'Cobquecura' },
    { value: 'coelemu', label: 'Coelemu' },
    { value: 'ninhue', label: 'Ninhue' },
    { value: 'portezuelo', label: 'Portezuelo' },
    { value: 'quirihue', label: 'Quirihue' },
    { value: 'ranquil', label: 'Ránquil' },
    { value: 'treguaco', label: 'Treguaco' },
    { value: 'san-carlos', label: 'San Carlos' },
    { value: 'coihueco', label: 'Coihueco' },
    { value: 'niquen', label: 'Ñiquén' },
    { value: 'san-fabian', label: 'San Fabián' },
    { value: 'san-nicolas', label: 'San Nicolás' },
  ],
  'biobio': [
    { value: 'concepcion', label: 'Concepción' },
    { value: 'coronel', label: 'Coronel' },
    { value: 'chiguayante', label: 'Chiguayante' },
    { value: 'florida', label: 'Florida' },
    { value: 'hualqui', label: 'Hualqui' },
    { value: 'lota', label: 'Lota' },
    { value: 'penco', label: 'Penco' },
    { value: 'san-pedro-de-la-paz', label: 'San Pedro de la Paz' },
    { value: 'santa-juana', label: 'Santa Juana' },
    { value: 'talcahuano', label: 'Talcahuano' },
    { value: 'tome', label: 'Tomé' },
    { value: 'hualpen', label: 'Hualpén' },
    { value: 'lebu', label: 'Lebu' },
    { value: 'arauco', label: 'Arauco' },
    { value: 'canete', label: 'Cañete' },
    { value: 'contulmo', label: 'Contulmo' },
    { value: 'curanilahue', label: 'Curanilahue' },
    { value: 'los-alamos', label: 'Los Álamos' },
    { value: 'tirua', label: 'Tirúa' },
    { value: 'los-angeles', label: 'Los Ángeles' },
    { value: 'antuco', label: 'Antuco' },
    { value: 'cabrero', label: 'Cabrero' },
    { value: 'laja', label: 'Laja' },
    { value: 'mulchen', label: 'Mulchén' },
    { value: 'nacimiento', label: 'Nacimiento' },
    { value: 'negrete', label: 'Negrete' },
    { value: 'quilaco', label: 'Quilaco' },
    { value: 'quilleco', label: 'Quilleco' },
    { value: 'san-rosendo', label: 'San Rosendo' },
    { value: 'santa-barbara', label: 'Santa Bárbara' },
    { value: 'tucapel', label: 'Tucapel' },
    { value: 'yumbel', label: 'Yumbel' },
    { value: 'alto-biobio', label: 'Alto Biobío' },
  ],
  'araucania': [
    { value: 'temuco', label: 'Temuco' },
    { value: 'carahue', label: 'Carahue' },
    { value: 'cunco', label: 'Cunco' },
    { value: 'curarrehue', label: 'Curarrehue' },
    { value: 'freire', label: 'Freire' },
    { value: 'galvarino', label: 'Galvarino' },
    { value: 'gorbea', label: 'Gorbea' },
    { value: 'lautaro', label: 'Lautaro' },
    { value: 'loncoche', label: 'Loncoche' },
    { value: 'melipeuco', label: 'Melipeuco' },
    { value: 'nueva-imperial', label: 'Nueva Imperial' },
    { value: 'padre-las-casas', label: 'Padre Las Casas' },
    { value: 'perquenco', label: 'Perquenco' },
    { value: 'pitrufquen', label: 'Pitrufquén' },
    { value: 'pucon', label: 'Pucón' },
    { value: 'saavedra', label: 'Saavedra' },
    { value: 'teodoro-schmidt', label: 'Teodoro Schmidt' },
    { value: 'tolten', label: 'Toltén' },
    { value: 'vilcun', label: 'Vilcún' },
    { value: 'villarrica', label: 'Villarrica' },
    { value: 'cholchol', label: 'Cholchol' },
    { value: 'angol', label: 'Angol' },
    { value: 'collipulli', label: 'Collipulli' },
    { value: 'curacautin', label: 'Curacautín' },
    { value: 'ercilla', label: 'Ercilla' },
    { value: 'lonquimay', label: 'Lonquimay' },
    { value: 'los-sauces', label: 'Los Sauces' },
    { value: 'lumaco', label: 'Lumaco' },
    { value: 'puren', label: 'Purén' },
    { value: 'renaico', label: 'Renaico' },
    { value: 'traiguen', label: 'Traiguén' },
    { value: 'victoria', label: 'Victoria' },
  ],
  'los-rios': [
    { value: 'valdivia', label: 'Valdivia' },
    { value: 'corral', label: 'Corral' },
    { value: 'lanco', label: 'Lanco' },
    { value: 'los-lagos', label: 'Los Lagos' },
    { value: 'mafil', label: 'Máfil' },
    { value: 'mariquina', label: 'Mariquina' },
    { value: 'paillaco', label: 'Paillaco' },
    { value: 'panguipulli', label: 'Panguipulli' },
    { value: 'la-union', label: 'La Unión' },
    { value: 'futrono', label: 'Futrono' },
    { value: 'lago-ranco', label: 'Lago Ranco' },
    { value: 'rio-bueno', label: 'Río Bueno' },
  ],
  'los-lagos': [
    { value: 'puerto-montt', label: 'Puerto Montt' },
    { value: 'calbuco', label: 'Calbuco' },
    { value: 'cochamo', label: 'Cochamó' },
    { value: 'fresia', label: 'Fresia' },
    { value: 'frutillar', label: 'Frutillar' },
    { value: 'los-muermos', label: 'Los Muermos' },
    { value: 'llanquihue', label: 'Llanquihue' },
    { value: 'maullin', label: 'Maullín' },
    { value: 'puerto-varas', label: 'Puerto Varas' },
    { value: 'castro', label: 'Castro' },
    { value: 'ancud', label: 'Ancud' },
    { value: 'chonchi', label: 'Chonchi' },
    { value: 'curaco-de-velez', label: 'Curaco de Vélez' },
    { value: 'dalcahue', label: 'Dalcahue' },
    { value: 'puqueldon', label: 'Puqueldón' },
    { value: 'queilen', label: 'Queilén' },
    { value: 'quellon', label: 'Quellón' },
    { value: 'quinchao', label: 'Quinchao' },
    { value: 'osorno', label: 'Osorno' },
    { value: 'puerto-octay', label: 'Puerto Octay' },
    { value: 'purranque', label: 'Purranque' },
    { value: 'puyehue', label: 'Puyehue' },
    { value: 'rio-negro', label: 'Río Negro' },
    { value: 'san-juan-de-la-costa', label: 'San Juan de la Costa' },
    { value: 'san-pablo', label: 'San Pablo' },
    { value: 'chaiten', label: 'Chaitén' },
    { value: 'futaleufu', label: 'Futaleufú' },
    { value: 'hualaihue', label: 'Hualaihué' },
    { value: 'palena', label: 'Palena' },
  ],
  'aysen': [
    { value: 'coyhaique', label: 'Coyhaique' },
    { value: 'lago-verde', label: 'Lago Verde' },
    { value: 'aysen', label: 'Aysén' },
    { value: 'cisnes', label: 'Cisnes' },
    { value: 'guaitecas', label: 'Guaitecas' },
    { value: 'cochrane', label: 'Cochrane' },
    { value: 'ohiggins', label: "O'Higgins" },
    { value: 'tortel', label: 'Tortel' },
    { value: 'chile-chico', label: 'Chile Chico' },
    { value: 'rio-ibanez', label: 'Río Ibáñez' },
  ],
  'magallanes': [
    { value: 'punta-arenas', label: 'Punta Arenas' },
    { value: 'laguna-blanca', label: 'Laguna Blanca' },
    { value: 'rio-verde', label: 'Río Verde' },
    { value: 'san-gregorio', label: 'San Gregorio' },
    { value: 'cabo-de-hornos', label: 'Cabo de Hornos' },
    { value: 'antartica', label: 'Antártica' },
    { value: 'porvenir', label: 'Porvenir' },
    { value: 'primavera', label: 'Primavera' },
    { value: 'timaukel', label: 'Timaukel' },
    { value: 'puerto-natales', label: 'Puerto Natales' },
    { value: 'torres-del-paine', label: 'Torres del Paine' },
  ],
};

// Función para obtener todas las ciudades
export const getAllCities = () => {
  const allCities = [];
  Object.values(ciudadesPorRegion).forEach(cities => {
    allCities.push(...cities);
  });
  return allCities;
};

// Función para obtener todas las comunas
export const getAllComunas = () => {
  const allComunas = [];
  Object.values(comunasPorRegion).forEach(comunas => {
    allComunas.push(...comunas);
  });
  return allComunas;
};

// Función para obtener ciudades por región
export const getCitiesByRegion = (regionValue) => {
  return ciudadesPorRegion[regionValue] || [];
};

// Función para obtener comunas por región
export const getComunasByRegion = (regionValue) => {
  return comunasPorRegion[regionValue] || [];
};

// Función para obtener comunas por ciudad (más específico)
export const getComunasByCity = (regionValue, cityValue) => {
  // Esta es una implementación simplificada
  // En un caso real, tendrías una relación más específica ciudad -> comunas
  return getComunasByRegion(regionValue);
};
