export { default as Register } from './register/components/Register.jsx';
export { useLoginForm } from './login/hooks/useLoginForm.js';
export { default as useTermsModal } from './register/hooks/useTermsModal.js';
export { default as authService } from './shared-services/authService.js';
export * from './shared-types/types.js';
export * from './shared-constants/constants.js';
export { default as AuthCallback } from './login/services/AuthCallback';
export { default as PrivateRoute } from './guards/components/PrivateRoute';
export { default as OnboardingForm } from './onboarding/components/OnboardingForm';
export { default as Timer } from '../../domains/auth/components/Timer';
